### ISSUE TITLE
Create github signup flow

### ISSUE THREAD

**Issue by renanivo** [renanivo/houserules#1]

**Comment by drgarcia1986** [comment]
I managed to make this flow :smile: 
Now I need to write some tests and make a lot refactor

I'll work for it :+1:

**Comment by renanivo** [comment]
@drgarcia1986 We will need the following scopes: `repo:status,admin:repo_hook`.

**Comment by drgarcia1986** [comment]
:+1:

**Comment by drgarcia1986** [comment]
@renanivo done (`git pull` FTW)

**Comment by drgarcia1986** [comment]
@renanivo What is missing to close this issue?

**Comment by renanivo** [comment]
Nothing! :smile:
