### ISSUE TITLE
code health

### ISSUE THREAD

**Issue by drgarcia1986** [renanivo/houserules#5]
IDK whats the best tool for this, maybe [landscape](landscape.io) or [quantifiedcode]( https://www.quantifiedcode.com).

I can't use landscape because I can't create my account :sob:

**Comment by luzfcb** [comment]
@drgarcia1986 ask for help to `carl {at} landscape {dot} io`

**Comment by renanivo** [comment]
@drgarcia1986 Let's talk about it, I know [codeclimate](https://codeclimate.com/github/renanivo/houserules) too.

**Comment by drgarcia1986** [comment]
Great, codeclimate is new for me.
