### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by drgarcia1986** [renanivo/houserules#7]
I'm starting something in another branch (docker).
But I will updating it when I getting sick of the other tasks :P

**Comment by drgarcia1986** [comment]
It's still necessary? I think no :stuck_out_tongue:

**Comment by renanivo** [comment]
Maybe it is. We will have to deploy it, eventually. A docker container could help.

**Comment by renanivo** [comment]
Did you started something about this task? If you didn't, I'd like to assign this task to myself. Currently, I have my hands dirty with devops stuff.

**Comment by drgarcia1986** [comment]
Sorry for delay, I'm starting this task in the past, but for now it's all in the trash.
Now it's in your hands 😄

**Comment by renanivo** [comment]
Done in PR #19
